services:
  playwright:
    build: .
    ipc: host
    environment:
      BASE_URL: ${BASE_URL:-https://playwright.dev}
      CI: 'true'
    volumes:
      - ./playwright-report:/app/playwright-report
      - ./test-results:/app/test-results
      - ./allure-results:/app/allure-results
